version: '3.7'

services:
  db:
    image: postgres:14.5-alpine
    volumes:
      - postgres_data:/var/lib/postgres/data/
    #      - ./app/db/sql/:/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

volumes:
  postgres_data:
