version: '3.7'

services:
  krakend:
    image: devopsfaith/krakend
    container_name: yiazou_krakend
    volumes:
      - ./config/krakend:/etc/krakend
    ports:
      - "8080:8080"
    command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]

  postgres:
    image: postgres:13.2
    restart: unless-stopped
    container_name: yiazou_postgres
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/
      - ./config/db/:/docker-entrypoint-initdb.d/
    env_file:
      - .env

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: yiazou_rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
