version: '3.7'

services:

  account:
    build: ./account
    ports:
      - "9010:9010"
    restart: always
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - ./account/.env.example

  storage:
    build: ./storage
    # ports:
    #   - "9010:9010"
    restart: always
    depends_on:
      - postgres
      - rabbitmq
    env_file:
      - ./storage/.env.example

  krakend:
    image: devopsfaith/krakend
    volumes:
      - ./config/krakend:/etc/krakend
    ports:
      - "8080:8080"
    command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]

  postgres:
    image: postgres:13.2
    restart: unless-stopped
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data/
      - ./config/db/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
