version: '3.7'

services:

  auth:
    build: ./auth
    ports:
      - "9040:9040"
    restart: always
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - AUT_DATABASE_URL=host=postgres user=postgres password=postgres dbname=postgres port=5432 sslmode=disable
      - AUT_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - AUT_PORT=9040
      - AUT_AUD=http://api.example.com
      - AUT_ISS=https://krakend.io

  filemanager:
    build: ./filemanager
    ports:
      - "9030:9030"
    restart: always
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - DATABASE_URL=host=postgres user=postgres password=postgres dbname=postgres port=5432 sslmode=disable
      - ACCOUNT_SERVICE=http://account:9010
      - STORAGE_SERVICE=http://storage:9020
      - PORT=9030

  account:
    build: ./account
    ports:
      - "9010:9010"
    restart: always
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - DATABASE_URL=host=postgres user=postgres password=postgres dbname=postgres port=5432 sslmode=disable
      - PORT=9010

  storage:
    build: ./storage
    ports:
      - "9020:9020"
    restart: always
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - STORAGE_PATH=/files/
      - PORT=9020
    volumes:
      - ./volumes/files/:/files/

  krakend:
    image: devopsfaith/krakend
    volumes:
      - ./config/krakend:/etc/krakend
    ports:
      - "8080:8080"
    command: ["run", "-d", "-c", "/etc/krakend/krakend.json"]

  postgres:
    image: postgres:13.2
    restart: unless-stopped
    volumes:
      # - ./volumes/postgres:/var/lib/postgresql/data/
      - ./config/db/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
