version: '3.7'

networks:
  intranet:


volumes:
  postgres_data:


services:
  # migration service. Stops after complete migration
  kratos-migrate:
    image: oryd/kratos:v0.13.0
    environment:
      # - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true&mode=rwc
      - DSN=postgres://postgres:postgres@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    volumes:
      - ./config/kratos:/etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    depends_on:
      - postgresd
    networks:
      - intranet

  # UI
  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v0.13.0
    environment:
      - PORT=4455
      - SECURITY_MODE=
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
      - KRATOS_PUBLIC_URL=http://kratos:4433/
    restart: on-failure
    ports:
      - "4455:4455"
    networks:
      - intranet

  # Itself
  kratos:
    depends_on:
      - kratos-migrate
      - postgresd
    image: oryd/kratos:v0.13.0
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      # - DSN=sqlite:///var/lib/sqlite/db.sqlite?_fk=true
      - DSN=postgres://postgres:postgres@postgresd:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=trace
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier
    volumes:
      - ./config/kratos:/etc/config/kratos
    networks:
      - intranet

  # mail server
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - intranet

  # Database
  postgresd:
    image: postgres:13.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_MULTIPLE_DATABASES=kratos,application
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./config/db/init/:/docker-entrypoint-initdb.d/
    networks:
      - intranet

  auth:
    build: ./auth
    ports:
      - "9040:9040"
    restart: always
    depends_on:
      - kratos
    environment:
      - AUTH_SERVER=http://kratos:4433
      - AUTH_SERVER_SESSION_NAME=ory_kratos_session
      - PORT=9040
    networks:
      - intranet

  krakend:
    image: devopsfaith/krakend
    volumes:
      - ./config/krakend:/etc/krakend
    ports:
      - "8080:8080"
    command: [ "run", "-d", "-c", "/etc/krakend/krakend.json" ]
    networks:
      - intranet
