version: "3.7"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_MULTIPLE_DATABASES=kratos,application
    ports:
      - 5432:5432
    volumes:
      - ./config/db/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: /usr/bin/pg_isready
      interval: 5s
      timeout: 10s
      retries: 120
    networks:
      - intranet

  # UI for authorization/registration processes
  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v0.13.0
    environment:
      - PORT=4455
      - SECURITY_MODE=
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
      - KRATOS_PUBLIC_URL=http://kratos:4433/
    restart: on-failure
    ports:
      - "4455:4455"
    networks:
      - intranet

  # NOTE: Ory/Kratos services
  application-migrate:
    build: ./application-migrate
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: user
      PGPASSWORD: password
      DB_NAME: application
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - intranet

  kratos-migrate:
    image: oryd/kratos:v0.13.0
    environment:
      - DSN=postgres://user:password@postgres:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    networks:
      - intranet
    volumes:
      - type: bind
        source: ./config/kratos
        target: /etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes

  kratos:
    image: oryd/kratos:v0.13.0
    environment:
      - DSN=postgres://user:password@postgres:5432/kratos?sslmode=disable&max_conns=20&max_idle_conns=4
    ports:
      - "4433:4433"
      - "4434:4434"
    volumes:
      - type: bind
        source: ./config/kratos
        target: /etc/config/kratos
    networks:
      - intranet
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier

  # Email service
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - "4436:4436"
      - "4437:4437"
    networks:
      - intranet

  # API Getway
  oathkeeper:
    image: oryd/oathkeeper:v0.40
    depends_on:
      - kratos
    ports:
      - 8080:4455
      - 4456:4456
    command: serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"
    environment:
      - LOG_LEVEL=debug
    restart: on-failure
    networks:
      - intranet
    volumes:
      - ./config/oathkeeper:/etc/config/oathkeeper

  # validate user Cookie and get User tratis (email, name{first,last})
  user:
    build: ./user
    networks:
      - intranet
    environment:
      - PORT=9040
      - KRATOS_PATH=http://kratos:4433

  filemanager:
    build: ./filemanager
    ports:
      - "9030:9030"
    restart: always
    depends_on:
      - postgres
      - rabbitmq
    environment:
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - DATABASE_URL=host=postgres user=user password=password dbname=application port=5432 sslmode=disable
      - STORAGE_SERVICE=http://storage:9020
      - PORT=9030
    networks:
      - intranet

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - intranet

networks:
  intranet:
