- id: "test_hello_service"
  upstream:
    preserve_host: true
    url: "http://hello:8090"
    strip_path: /api/v2
  match:
    url: "http://127.0.0.1:8080/api/v2/hello<**>"
    methods:
      - GET
      - POST
  authenticators:
    - handler: cookie_session
  mutators:
    - handler: header
  authorizer:
    handler: allow
  errors:
    - handler: redirect
      config:
        to: http://127.0.0.1:4455/login


- id: "filemanager"
  upstream:
    preserve_host: true
    url: "http://filemanager:9030"
    strip_path: /api/v2
  match:
    url: "http://127.0.0.1:8080/api/v2/files/<**>"
    methods:
      - GET
      - POST
  authenticators:
    - handler: cookie_session
  mutators:
    - handler: header
  authorizer:
    handler: allow
  errors:
    - handler: redirect
      config:
        to: http://127.0.0.1:4455/login
