[db]
path = "database.db"

[admin]
email = "email@email.com"
name = "Test Name"
password = "password"

[storage]
path = "./storage/"

[web]
port = 5000
host = "localhost"
public_link = "localhost:5000"
session_name = "hfs_session"
secret_key = "test-secret-key"

[csrf]
csrf_string = "test-csrf-string"
# TODO: generete it once on first start?
# openssl rand -base64 42 