[db]
path = "database.db"

[admin]
email = "email@email.com"
name = "Test Name"
password = "password"

[storage]
path = "./storage/"

[gin]
mode = "debug"  # release, debug, test
port = 8080

[web]
port = 5000
