[db]
path = "database.db"

[admin]
email = "email@email.com"
name = "Test Name"
password = "password"

[storage]
path = "./storage/"

[gin]
mode = "debug"  # release, debug, test
port = 8080

[web]
port = 5000

[csrf]
csrf_string = "8cpX8olZkhNLMr06gPOW+lk98CubyIVur2YgOA+Pg54Mn3fH6lXERiZg"
# TODO: generete it once on first start?
# openssl rand -base64 42 