name: Test Account Service

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: [1.16, 1.17, 1.18, 1.19, 1.20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test -v ./account/...

      - name: Merge pull request
        if: success() && github.event.action == 'opened'
        uses: peter-evans/create-pull-request@v3.11.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          title: ${{ github.event.pull_request.title }}
          body: ${{ github.event.pull_request.body }}
          commit-message: ${{ github.event.pull_request.title }}